;;; Scheme Recursive Art Contest Entry
;;;
;;; Please do not include your name or personal info in this file.
;;;
;;; Title: Golden Bear Comes
;;;
;;; Description:
;;;   <Winter is here
;;;    Falling so hard, snowflakes
;;;    Golden Bear comes, rainbow.>

(define (draw)
(begin
    (bgcolor "black")
    (right 90)
    (draw_tree)
    (bgpic "bear.gif")
    (penup)
    (left 45)
    (fd 380)
    (color "white")
    (pendown)
    (draw_snowflake 50 5)
    (penup)
    (left 120)
    (fd 100)
    (pendown)
    (draw_snowflake 25 4)
    (penup)
    (left 120)
    (fd 100)
    (pendown)
    (draw_snowflake 20 4)
    (penup)
    (right 90)
    (fd 200)
    (pendown)
    (draw_snowflake 30 4)
    (penup)
    (right 45)
    (fd 200)
    (pendown)
    (draw_snowflake 40 4)
    (penup)
    (left 90)
    (fd 130)
    (pendown)
    (draw_snowflake 70 5))


  (exitonclick))


(define (tree size level)
    (if (= level 1)
        (begin (fd size)
        (bk size))
    (begin
        (fd size)
        (left 15)
        (tree (* size 0.75) (- level 1))
        (right 30)
        (tree (* size 0.75) (- level 1))
        (left 15)
        (bk size))))

(define (draw_tree)
    (begin
        (color "yellow")
        (tree 100 6)
        (right 15)
        (color "orange")
        (tree 100 6)
        (right 15)
        (color "coral")
        (tree 100 6)
        (right 15)
        (color "orangered")
        (tree 100 6)
        (right 15)
        (color "red")
        (tree 100 6)
        (right 15)
        (color "deeppink")
        (tree 100 6)
        (right 15)
        (color "hotpink")
        (tree 100 6)
        (right 15)
        (color "pink")
        (tree 100 6)
        (right 15)
        (color "plum")
        (tree 100 6)
        (right 15)
        (color "violet")
        (tree 100 6)
        (right 15)
        (color "mediumorchid")
        (tree 100 6)
        (right 15)
        (color "darkmagenta")
        (tree 100 6)
        (right 15)
        (color "mediumpurple")
        (tree 100 6)
        (right 15)
        (color "slateblue")
        (tree 100 6)
        (right 15)
        (color "darkslateblue")
        (tree 100 6)
        (right 15)
        (color "royalblue")
        (tree 100 6)
        (right 15)
        (color "dodgerblue")
        (tree 100 6)
        (right 15)
        (color "deepskyblue")
        (tree 100 6)
        (right 15)
        (color "turquoise")
        (tree 100 6)
        (right 15)
        (color "lightseagreen")
        (tree 100 6)
        (right 15)
        (color "darkcyan")
        (tree 100 6)
        (right 15)
        (color "forestgreen")
        (tree 100 6)
        (right 15)
        (color "limegreen")
        (tree 100 6)
        (right 15)
        (color "greenyellow")
        (tree 100 6)
        (right 15)))
        



(define (snowflake size level)
    (if (= level 1) (fd size)
        (begin
        (snowflake (/ size 3) (- level 1))
        (left 60)
        (snowflake (/ size 3) (- level 1))
        (right 120)
        (snowflake (/ size 3) (- level 1))
        (left 60)
        (snowflake (/ size 3) (- level 1)))))

(define (draw_snowflake size level)
    (begin
    (snowflake size level)
    (right 120)
    (snowflake size level)
    (right 120)
    (snowflake size level)
    (right 120)))

; Please leave this last line alone.  You may add additional procedures above
; this line.  All Scheme tokens in this file (including the one below) count
; toward the token limit.

(draw)